version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: dreamshops-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dreamshops
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: .
    container_name: dreamshops-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dreamshops
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql

volumes:
  db_data: